### ISSUE TITLE
index.php does not display section numbers 

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_collaborativefolders#12]
[original reporter: @tobiasreischmann]

**Comment by Dagefoerde** [comment]
During working on this issue, I discovered that the handling of repeated section names was wrong – this is now fixed.
However, I cannot see the original motivation behind this issue anymore. Other activities also don't show the section number. I checked against mod_forum, mod_assign, and mod_ratingallocate. The latter does not even show section names, though.

@tobiasreischmann what was your original intention / role model here?

**Comment by tobiasreischmann** [comment]
won't fix.
