### ISSUE TITLE
Enforce a folder structure that supports more than one application

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_collaborativefolders#29]
The plugin uses the technical user ("System account") in order to manage folders. However, right now it assumes it works alone, and creates folders per instance in the root directory of the technical user. This may lead to problems if other plugins want to use the same account and might use the same folder structure.

Expected:
At the root level, the plugin should define a specific folder structure that is unique to this plugin (or, at least, very speaking), so that it does not conflict with other plugins. Folders per instance will be created below this folder structure, instead of at root level.

**Comment by Dagefoerde** [comment]
This needs to be resolved before a public release, because this will definitely break all existing shares.

**Comment by Dagefoerde** [comment]
For reference, the `onedrive` and `googledocs` repository plugins create a folder structure:

- https://github.com/moodle/moodle/blob/5b4ca9eb5b12f3df982219504f3f1cef813c0a1d/repository/onedrive/lib.php#L901
- https://github.com/moodle/moodle/blob/5b4ca9eb5b12f3df982219504f3f1cef813c0a1d/repository/googledocs/lib.php#L953

The structure created by this plugin should follow a similar approach.

**Comment by davosmith** [comment]
I've written a fix for this and will open a pull request once it has gone through our internal testing.

**Comment by Dagefoerde** [comment]
Thanks, Davo, that's great to hear!

**Comment by Dagefoerde** [comment]
Closed via #34
