### ISSUE TITLE
More explicit selectors in styles.css

### ISSUE THREAD

**Issue by mudrd8mz** [learnweb/moodle-mod_collaborativefolders#40]
The selectors in the styles.css should ideally contain the component name, e.g.

```
.path-mod-collaborativefolders .groupfolderinfo.details.generaltable th {
    // ...
}
```

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#CSS_styles

**Comment by Dagefoerde** [comment]
Isn't it always great when you're thinking "who did this?" and you do a `git blame` and, well, you were the author yourself? :smile: Blame on me!

Anyway, well spotted. Will provide a patch.

**Comment by mudrd8mz** [comment]
Wow, I wish I was same effective in fixing reported issues in my own plugins! Well done and thanks.

**Comment by Dagefoerde** [comment]
Well, it was a simple one and you basically provided the patch already ;) Thank you
