### ISSUE TITLE
Verbindung zur Nextcloud klappt nicht

### ISSUE THREAD

**Issue by kueppersf** [learnweb/moodle-mod_collaborativefolders#41]
Hallo!
Wenn ich einen Collaborativfolder einrichten möchte erhalte ich die folgenden Fehlermeldung:

Unable to share the folder with you: WebDAV error code 403

Habt ihr eine Lösung dafür?

Viele Grüße
Friedhelm

**Comment by Dagefoerde** [comment]
Hallo Friedhelm, nutzt du die aktuellste Version von mod_collaborativefolders? Was für Meldungen tauchen in den Nextcloud-Access- und Error-Logs auf?

**Comment by kueppersf** [comment]
Hallo Jan,

 

danke für die Rückmeldung. Es geht mittlerweile. Ich hatte übersehen, das Webdav als Repository nicht aktiviert war. Danach hat es geklappt. 

 

Viele Grüße

Friedhelm

 

Von: Jan <notifications@github.com> 
Gesendet: Freitag, 17. Januar 2020 10:10
An: learnweb/moodle-mod_collaborativefolders <moodle-mod_collaborativefolders@noreply.github.com>
Cc: kueppersf <kueppers@nibis.de>; Author <author@noreply.github.com>
Betreff: Re: [learnweb/moodle-mod_collaborativefolders] Verbindung zur Nextcloud klappt nicht (#41)

 

Hallo Friedhelm, nutzt du die aktuellste Version von mod_collaborativefolders? Was für Meldungen tauchen in den Nextcloud-Access- und Error-Logs auf?

**Comment by fishfree** [comment]
@kueppersf Hello Kuppersf, I have the same problem. How did you solve it? Could you share m some details, please?
