### ISSUE TITLE
Fix access restrictions

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_collaborativefolders#9]
If you create a collaborative folder with teacher-access and group-mode, students which are in no group at all can create a share for the teachers' root folder.
Additionally, we have to think about what should happen if:
*  ~Students are in multiple groups?~ (resolved)
*  Students change their group after the share is established?
* What permissions do students have that are not in any group? (Expected: none. Actual: ??)
* What should happen for groups that are created after the activity has been created? (see comment by @davosmith below)

[original reporter: @tobiasreischmann]

**Comment by Dagefoerde** [comment]
Students are in multiple groups? -> solved. For each group that a student is in, an individual folder is displayed, ready to be shared.

This will also work if students change groups, however, their old shares (relating to former groups) remain assigned.

**Comment by Dagefoerde** [comment]
Original issue remains relevant as well: What can students do who are in no group? -> needs further investigation!

**Comment by davosmith** [comment]
Note - a related issue is that groups created after the activity do not get folders created for them.

**Comment by Dagefoerde** [comment]
Yes, indeed. I added this to the list in the first post.

**Comment by davosmith** [comment]
I'm looking at removing the task to create the folders and instead create each folder 'on demand', the first time a user from that group requests access.

i.e. check to see if there is a folder with the matching name, if there isn't, create it + share it, otherwise just share it.

**Comment by Dagefoerde** [comment]
That approach makes sense. Just to make sure (and with #2 in mind), is the name of the folder still just the group id? In that case I agree with your solution. However, this becomes a lot more complicated if the folder name contains some additional string based on the group name.

In my opinion, the folder name can continue to be just the group id. We can make the folder structure more accessible by other means if that becomes necessary.

**Comment by Dagefoerde** [comment]
Hi @davosmith, I heard that the work on this issue and the others was finalised successfully. Are you going to submit a pull request that contains all the changes or do I add them myself based on the last zip archive that we received from you? I am fine with either.

**Comment by davosmith** [comment]
Hi @Dagefoerde the code is finished as far as I am concerned, but I haven't heard confirmation that it is all OK (I simply haven't had any further UAT tickets passed back to me to look at). I'll double-check the situation, then I can add my commits to a public github repo and open a pull request (they are currently in a private bitbucket repo).

**Comment by Dagefoerde** [comment]
Hi @davosmith that would be great, thank you!

**Comment by Dagefoerde** [comment]
Fixed via #34, folder is now created on demand.
